#!/usr/bin/env python3
"""Generate Localizable.xcstrings + L10nKeys.swift from mobile/src/lib/i18n.ts of the Expo app.

Usage: python3 scripts/gen_l10n.py path/to/printshare/mobile/src/lib/i18n.ts
The output is committed; run this only when the Expo texts change.
"""
import json, re, sys, pathlib

src = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
STR = r'"((?:[^"\\]|\\.)*)"'
TABLES = ["jobStates", "printerKinds", "rawStates", "plates", "lineTypes", "heaterNames", "fanNames", "lightNames",
          "speedModes"]
PREFIX = {"jobStates": "jobState", "printerKinds": "printerKind", "rawStates": "rawState", "plates": "plate",
          "lineTypes": "lineType", "heaterNames": "heater", "fanNames": "fan", "lightNames": "light",
          "speedModes": "speedMode"}


def block(name_re: str) -> str:
    m = re.search(name_re, src)
    start = m.end()
    depth, i = 1, start
    while depth:
        ch = src[i]
        if ch == "{": depth += 1
        elif ch == "}": depth -= 1
        i += 1
    return src[start:i - 1]


def unesc(s: str) -> str:
    return json.loads('"' + s + '"')


def parse(body: str) -> dict:
    out = {}
    for tname in TABLES:
        m = re.search(tname + r":\s*\{", body)
        if not m:
            continue
        depth, i = 1, m.end()
        while depth:
            depth += {"{": 1, "}": -1}.get(body[i], 0)
            i += 1
        inner = body[m.end():i - 1]
        for q, k, v in re.findall(r'(?:"([\w ]+)"|(\b\w+)):\s*' + STR, inner):
            out[f"{PREFIX[tname]}.{q or k}"] = unesc(v)
        body = body[:m.start()] + body[i:]
    body = re.sub(r"log:\s*\[.*?\]\s*(as \[RegExp, string\]\[\])?,", "", body, flags=re.S)
    for k, v in re.findall(r'\b(\w+):\s*' + STR, body):
        out[k] = unesc(v)
    return out


de = parse(block(r"const de = \{"))
en = parse(block(r"const en: Strings = \{"))
# English line types are OrcaSlicer's own names: i18n.ts only lists the ones it renames
for k in de:
    if k.startswith("lineType.") and k not in en:
        en[k] = k.split(".", 1)[1]
assert set(de) == set(en), (set(de) ^ set(en))

# Texts only the native app has (share sheet, camera permission …). Keys that i18n.ts has by now are taken from there.
EXTRA = {
    "preview": ("Vorschau", "Preview"),
    "previewEmpty": ("Keine Vorschau verfügbar.", "No preview available."),
    "viewModel": ("Modell", "Model"),
    "viewBed": ("Platte", "Bed"),
    "layerOf": ("Schicht {n} von {total}", "Layer {n} of {total}"),
    "zHeight": ("Höhe {z} mm", "Height {z} mm"),
    "levelBed": ("Bett vor dem Druck nivellieren", "Level the bed before printing"),
    "lineTypes": ("Linientypen", "Line types"),
    "prevLayer": ("Vorherige Schicht", "Previous layer"),
    "nextLayer": ("Nächste Schicht", "Next layer"),
    "close": ("Schließen", "Close"),
    "openSettings": ("Einstellungen öffnen", "Open settings"),
    "cameraDenied": ("Der Kamerazugriff ist ausgeschaltet. Du kannst ihn in den Einstellungen erlauben.",
                     "Camera access is turned off. You can allow it in Settings."),
    "shareOpen": ("In PrintShare öffnen", "Open in PrintShare"),
    "serverVersionLabel": ("Server-Version", "Server version"),
    "shareGcode": ("G-Code teilen", "Share G-code"),
    "model3dUnsupported": ("Für {ext}-Dateien gibt es keine 3D-Ansicht. Drucken kannst du sie trotzdem.",
                           "There is no 3D view for {ext} files. You can still print them."),
    "model3dHint": ("Mit einem Finger drehen, mit zwei Fingern zoomen.", "Drag to rotate, pinch to zoom."),
    "errServerOld": ("Dein PrintShare-Server kennt diese Funktion noch nicht. Aktualisiere ihn auf die neueste Version.",
                     "Your PrintShare server does not have this feature yet. Update it to the latest version."),
}
for k, (d_, e_) in EXTRA.items():
    if k not in de:
        de[k], en[k] = d_, e_

strings = {}
for k in sorted(de):
    strings[k] = {"localizations": {
        "de": {"stringUnit": {"state": "translated", "value": de[k]}},
        "en": {"stringUnit": {"state": "translated", "value": en[k]}}}}
root = pathlib.Path(__file__).resolve().parent.parent
(root / "PrintShare/Resources/Localizable.xcstrings").write_text(
    json.dumps({"sourceLanguage": "de", "strings": strings, "version": "1.0"}, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8")


def case(k: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", k)


lines = ["// Generated by scripts/gen_l10n.py from the Expo app's i18n.ts - do not edit.", "",
         "enum L10nKey: String, CaseIterable, Sendable {"]
for k in sorted(de):
    lines.append(f'    case {case(k)} = "{k}"')
lines.append("}")
(root / "PrintShare/Util/L10nKeys.swift").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(len(de), "keys")
